# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "RMK Keyboard"
product_name = "RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
matrix_type = "direct_pin"
# `direct_pin_low_active` is optional. Default to `true`.
direct_pin_low_active = true
direct_pins = [
["P0_29", "P0_02", "P1_15"], 
["P1_13", "P1_11", "P0_10"], 
["P0_08", "P0_06", "P0_24"], 
["P1_00", "P0_11", "P1_04"],
]

[layout]
rows = 4
cols = 3
layers = 2
keymap = [
    [
        ["A", "B", "C"],
        ["D", "E", "F"],
        ["G", "H", "I"],
        ["J", "K", "L"]
    ],
    [
        ["Kc1", "Kc2", "Kc3"],
        ["Kc4", "Kc5", "Kc6"],
        ["Kc7", "Kc8", "Kc9"],
        ["Kc1", "Kc0", "Kc3"]
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true



[storage]
# Storage feature is enabled by default
# enabled = false
