name: Build RMK firmware
on:
  workflow_dispatch:
    inputs:
      run_deploy:
        description: 'Do you want to deploy?'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  build:
    uses: haobogu/rmk/.github/workflows/user_build.yml@main
    with:
      keyboard_toml_path: "keyboard.toml"
      vial_json_path: "vial.json"
